// flow-typed signature: 71d1127c14b8807d406176ec5f2753e6
// flow-typed version: <<STUB>>/npm-install-peers_v^1.2.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-install-peers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-install-peers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-install-peers/bin/npm-install-peers' {
  declare module.exports: any;
}

declare module 'npm-install-peers/dist/index' {
  declare module.exports: any;
}

declare module 'npm-install-peers/dist/package' {
  declare module.exports: any;
}

declare module 'npm-install-peers/src/index' {
  declare module.exports: any;
}

declare module 'npm-install-peers/src/package' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-install-peers/bin/npm-install-peers.js' {
  declare module.exports: $Exports<'npm-install-peers/bin/npm-install-peers'>;
}
declare module 'npm-install-peers/dist/index.js' {
  declare module.exports: $Exports<'npm-install-peers/dist/index'>;
}
declare module 'npm-install-peers/dist/package.js' {
  declare module.exports: $Exports<'npm-install-peers/dist/package'>;
}
declare module 'npm-install-peers/src/index.js' {
  declare module.exports: $Exports<'npm-install-peers/src/index'>;
}
declare module 'npm-install-peers/src/package.js' {
  declare module.exports: $Exports<'npm-install-peers/src/package'>;
}
